/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    AvatarList: typeof import('./src/components/avatar/AvatarList.vue')['default']
    BarChart: typeof import('./src/components/chart/BarChart.vue')['default']
    BlankView: typeof import('./src/components/layout/BlankView.vue')['default']
    CommonView: typeof import('./src/components/layout/CommonView.vue')['default']
    DayNightSwitch: typeof import('./src/components/switch/DayNightSwitch.vue')['default']
    EditableCell: typeof import('./src/components/editable-cell/EditableCell.vue')['default']
    FrontView: typeof import('./src/components/layout/FrontView.vue')['default']
    Fullscreen: typeof import('./src/components/fullscreen/Fullscreen.vue')['default']
    GridList: typeof import('./src/components/list/GridList.vue')['default']
    Guider: typeof import('./src/components/guider/Guider.vue')['default']
    HeaderActions: typeof import('./src/components/layout/HeaderActions.vue')['default']
    IconSelector: typeof import('./src/components/selector/IconSelector.vue')['default']
    LineChart: typeof import('./src/components/chart/LineChart.vue')['default']
    LinkView: typeof import('./src/components/layout/LinkView.vue')['default']
    MiniStatisticCard: typeof import('./src/components/statistic/MiniStatisticCard.vue')['default']
    Notice: typeof import('./src/components/notice/Notice.vue')['default']
    OverviewTitle: typeof import('./src/components/statistic/OverviewTitle.vue')['default']
    PageFooter: typeof import('./src/components/layout/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/setting/Setting.vue')['default']
    Splitter: typeof import('./src/components/format/Splitter.vue')['default']
  }
}
